// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ButtonController from "./button_controller"
application.register("button", ButtonController)

import CheckifdateController from "./checkifdate_controller"
application.register("checkifdate", CheckifdateController)

// import ClipboardController from "./clipboard_controller"
// application.register("clipboard", ClipboardController)

import FavoriteController from "./favorite_controller"
application.register("favorite", FavoriteController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import SpeedTestController from "./speed_test_controller"
application.register("speed-test", SpeedTestController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

// import WifiController from "./wifi_controller"
// application.register("wifi", WifiController)
