// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ButtonController from "./button_controller"
application.register("button", ButtonController)

import CheckifdateController from "./checkifdate_controller"
application.register("checkifdate", CheckifdateController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import SpeedtestController from "./speedtest_controller"
application.register("speedtest", SpeedtestController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import CheckIfDateController from "./checkifdate_controller"
application.register("checkifdate", CheckIfDateController)

import FavoriteController from "./favorite_controller"
application.register("favorite", FavoriteController)

import WifiController from "./wifi_controller"
application.register("wifi", WifiController)